/** Bride & groom photos — add or remove files in public/images/bride-groom/ and update this list. */
export const galleryImages = [
  // "/images/bride-groom/d1.jpeg",
  "/images/bride-groom/d3.jpeg",
  "/images/bride-groom/ds1.jpeg",
  "/images/bride-groom/ds2.jpeg",
  "/images/bride-groom/ds3.jpeg",
  "/images/bride-groom/ds4.jpeg",
  "/images/bride-groom/ds5.jpeg",
  "/images/bride-groom/ds6.jpeg",
  "/images/bride-groom/ds7.jpeg",
  "/images/bride-groom/ds8.jpeg",
  "/images/bride-groom/ds9.jpeg",
  "/images/bride-groom/ds10.jpeg",
  "/images/bride-groom/ds11.jpeg",
  "/images/bride-groom/ds12.jpeg",
  "/images/bride-groom/ds13.jpeg",
  "/images/bride-groom/ds14.jpeg",
  "/images/bride-groom/ds15.jpeg",
  "/images/bride-groom/ds16.jpeg",
  "/images/bride-groom/ds17.jpeg",
  "/images/bride-groom/ds18.jpeg",
  "/images/bride-groom/ds19.jpeg",
  "/images/bride-groom/ds20.jpeg",
  "/images/bride-groom/ds21.jpeg",
  "/images/bride-groom/ds22.jpeg",
  // "/images/bride-groom/ds23.jpeg",
  "/images/bride-groom/s1.jpeg",
  "/images/bride-groom/s2.jpeg",
] as const;
